# Run, use, stop, restart the anchore-engine with docker-compose
# - run: docker-compose up -d
#
# - interact with anchore-engine with anchore-cli:
#   - export ANCHORE_CLI_URL=http://localhost:8228/v1
#   - export ANCHORE_CLI_USER=admin
#   - export ANCHORE_CLI_PASS=foobar
#   - export ANCHORE_CLI_SSL_VERIFY=n
#   - anchore-cli image list
#   - anchore-cli image add alpine
#   - anchore-cli image get alpine
#   - ...
#
# - stop: docker-compose down --volumes
#
# Notes:
# - to start up again, run the same docker-compose up -d as above
# - to reset the DB, stop anchore engine with docker-compose down --volumes as above, then remove all files/directories in ~/aevolume/db/*, and restart
# - if you enable SSL for any services, make sure to do so across the board in your config.yaml, and change the ANCHORE_CLI_URL to use https instead of http
# - if you change the admin password in config.yaml, make sure to update your ANCHORE_CLI_PASS export as well
# - if you change the DB password in this file, make sure to also change it in your config.yaml 'db_connect' setting
# 

version: '3'
services:
  anchore-engine:
    image: docker.io/anchore/anchore-engine:latest
    #privileged: true
    depends_on:
     - anchore-db
    ports:
     - "8228:8228"
     - "8338:8338"
    volumes:
     - ${PWD}/config:/config/:Z
     #- /var/run/docker.sock:/var/run/docker.sock
    environment:
     # NOTE: this should be set to the same name as this service (e.g. anchore-engine)
     - ANCHORE_HOST_ID=anchore-engine
  anchore-db:
    image: "postgres:9"
    volumes:
     - ${PWD}/db:/var/lib/postgresql/data/pgdata/:Z
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata/
    #uncomment to expose a port to allow direct/external access to the DB, for debugging
    #ports:
    # - "2345:5432"
#### uncomment this section to enable a prometheus service running alongside anchore-engine for metrics gathering/display
#  anchore-prometheus:
#    image: docker.io/prom/prometheus:latest
#    depends_on:
#     - anchore-engine
#    volumes:
#     - ${PWD}/anchore-prometheus.yml:/etc/prometheus/prometheus.yml:Z
#    ports:
#     - "9090:9090"
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-master
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - "${PWD}/jenkins:/var/jenkins_home"
