FROM jenkins/jenkins:lts-alpine
USER root
RUN apk update && apk upgrade
USER jenkins
RUN /usr/local/bin/install-plugins.sh \
    workflow-aggregator \
    git \
    credentials-binding \
    ws-cleanup \
    anchore-container-scanner \
    matrix-auth

# vim:syn=dockerfile:
